# Generated by Django 3.1.7 on 2021-04-26 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schletter_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'theater', 'title']},
        ),
    ]
