# Generated by Django 3.1.7 on 2021-04-26 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schletter_app', '0002_auto_20210426_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['pk']},
        ),
    ]
