# Generated by Django 3.1.7 on 2021-05-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schletter_app', '0003_auto_20210426_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='source_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
