# Generated by Django 3.1.7 on 2021-05-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schletter_app', '0004_work_source_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='source_genre',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='work',
            name='genre',
            field=models.CharField(max_length=75),
        ),
    ]
