# Generated by Django 3.1.7 on 2021-06-01 23:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schletter_app', '0005_auto_20210529_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='notes',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='composer',
            name='notes',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='notes',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
