# Generated by Django 3.1.7 on 2021-06-02 20:32

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('schletter_app', '0006_auto_20210601_2323'),
    ]

    operations = [
        UnaccentExtension(),
    ]
