# Generated by Django 3.1.7 on 2021-06-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schletter_app', '0007_auto_20210602_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='title_page',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
