# Generated by Django 3.1.7 on 2021-06-22 14:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schletter_app', '0008_work_title_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='title_page',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
