# Generated by Django 4.2.3 on 2024-03-03 02:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schletter_app', '0009_auto_20210622_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
