# Generated by Django 4.2.3 on 2024-03-03 21:50

from django.db import migrations, models

def reorder(apps, schema_editor):
    Event = apps.get_model("schletter_app", "Event")
    for order, item in enumerate(Event.objects.all(), 1):
        item.event_order = order
        item.save(update_fields=['event_order'])

class Migration(migrations.Migration):

    dependencies = [
        ('schletter_app', '0010_alter_event_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'theater']},
        ),
        migrations.AddField(
            model_name='event',
            name='event_order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(reorder, reverse_code=migrations.RunPython.noop),
    ]
