# Generated by Django 4.2.3 on 2024-03-03 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schletter_app', '0011_alter_event_options_event_event_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_order']},
        ),
    ]
