# Generated by Django 4.2.3 on 2024-03-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schletter_app', '0013_alter_work_sort_title_alter_work_source_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
