# Generated by Django 4.2.3 on 2024-03-16 20:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schletter_app', '0014_alter_work_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorwork',
            options={'ordering': ['author__last_name']},
        ),
        migrations.AlterModelOptions(
            name='composerwork',
            options={'ordering': ['composer__last_name']},
        ),
        migrations.AlterModelOptions(
            name='workevent',
            options={'ordering': ['event__event_order']},
        ),
        migrations.AlterField(
            model_name='author',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='composer',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
