# Generated by Django 4.2.3 on 2024-03-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schletter_app', '0017_about_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='slug',
        ),
    ]
