# Generated by Django 4.2.3 on 2024-04-02 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schletter_app', '0019_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
    ]
