# Generated by Django 3.1.7 on 2021-04-11 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater', models.CharField(max_length=3)),
                ('company', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('composer', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schletter_test.date')),
            ],
        ),
    ]
