# Generated by Django 3.1.7 on 2021-04-12 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('theater', models.CharField(max_length=3)),
                ('company', models.CharField(max_length=10)),
                ('event_type', models.CharField(max_length=50)),
                ('hadamowsky', models.CharField(max_length=5)),
                ('morrow', models.CharField(max_length=5)),
                ('notes', models.TextField(blank=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schletter_test.date')),
            ],
            options={
                'ordering': ['date', 'theater'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sort_title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('url', models.URLField()),
                ('author', models.CharField(max_length=100)),
                ('composer', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='WorkEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schletter_test.event')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schletter_test.work')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='events',
            field=models.ManyToManyField(through='schletter_test.WorkEvent', to='schletter_test.Event'),
        ),
    ]
