# Generated by Django 3.1.7 on 2021-03-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schletter_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='composer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
