# Generated by Django 3.1.7 on 2021-04-13 17:09

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('schletter_test', '0003_auto_20210413_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='notes',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='workevent',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
