# Generated by Django 3.1.7 on 2021-04-16 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schletter_test', '0004_auto_20210413_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_names', models.CharField(max_length=200)),
                ('birth', models.IntegerField()),
                ('death', models.IntegerField()),
                ('notes', models.TextField()),
            ],
            options={
                'ordering': ['last_name', 'first_names'],
            },
        ),
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_names', models.CharField(max_length=200)),
                ('birth', models.IntegerField()),
                ('death', models.IntegerField()),
                ('notes', models.TextField()),
            ],
            options={
                'ordering': ['last_name', 'first_names'],
            },
        ),
        migrations.CreateModel(
            name='ComposerWork',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schletter_test.composer')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schletter_test.work')),
            ],
        ),
        migrations.AddField(
            model_name='composer',
            name='works',
            field=models.ManyToManyField(related_name='composerworks', through='schletter_test.ComposerWork', to='schletter_test.Work'),
        ),
        migrations.CreateModel(
            name='AuthorWork',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schletter_test.author')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schletter_test.work')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='works',
            field=models.ManyToManyField(related_name='authorworks', through='schletter_test.AuthorWork', to='schletter_test.Work'),
        ),
    ]
