# Generated by Django 3.1.7 on 2021-04-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schletter_test', '0005_auto_20210416_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='author',
        ),
        migrations.RemoveField(
            model_name='work',
            name='composer',
        ),
    ]
