# Generated by Django 3.1.7 on 2021-04-17 00:00

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('schletter_test', '0006_auto_20210416_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='notes',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
